name: Go build
run-name: Pipeline run by @${{ github.actor }} on ${{ github.ref}} 🚀

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}


    - name: Go Build
      run: |
        for module in $(find go -name go.mod -exec dirname {} \;); do
          cd $module
          go build -o ./$(basename $module) ./
          cd -
        done

    - name: Go Test
      run: |
        for module in $(find go -name go.mod -exec dirname {} \;); do
          cd $module
          go test -v -coverprofile=coverage.out ./...
          go tool cover -html=coverage.out
          cd -
        done

    - name: Test with shell
      run: |
        for module in $(find go -name go.mod -exec dirname {} \;); do
          cd $module/tests
          ./test.sh -p ../$(basename $module)
          cd -
        done
