name: Go build
run-name: Pipeline run by @${{ github.actor }} on ${{ github.ref}} 🚀

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.21"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go-version }}

    - name: Go Build
      run: |
        cd go/wc
        go build  -o ./wc ./

    - name: Go Test
      run: |
        cd go/wc
        go test -v ./...

    - name: Test with shell
      run: |
        cd go/wc/tests
        ./test.sh -p ../wc
